INSERT INTO config_commandalias VALUES(1,'l','look');
INSERT INTO config_commandalias VALUES(2,'ex','examine');
INSERT INTO config_commandalias VALUES(3,'@dest','@destroy');
INSERT INTO config_commandalias VALUES(4,'@nuke','@destroy');
INSERT INTO config_commandalias VALUES(5,'sa','say');
INSERT INTO config_commandalias VALUES(6,'@tel','@teleport');
INSERT INTO config_commandalias VALUES(7,'i','inventory');
INSERT INTO config_commandalias VALUES(8,'inv','inventory');
INSERT INTO config_commandalias VALUES(9,'@desc','@describe');
