# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 02:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20190128_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdb',
            name='db_sessid',
            field=models.CharField(help_text='csv list of session ids of connected Account, if any.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='session id'),
        ),
    ]
