# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 23:11
from __future__ import unicode_literals

from django.db import migrations
import evennia.utils.picklefield


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='db_value',
            field=evennia.utils.picklefield.PickledObjectField(help_text='The data returned when the config value is accessed. Must be written as a Python literal if editing through the admin interface. Attribute values which are not Python literals cannot be edited through the admin interface.', null=True, verbose_name='value'),
        ),
    ]
