# Generated by Django 4.0.2 on 2022-10-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_auto_20190128_2311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
