# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190128_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfig',
            name='db_value',
        ),
        migrations.RenameField(
            model_name='serverconfig',
            old_name='db_value2',
            new_name='db_value',
        ),
    ]
