# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-21 22:30
from __future__ import unicode_literals

from django.db import migrations

def update_tags_with_dbmodel(apps, schema_editor):
    Tag = apps.get_model('typeclasses', 'Tag')
    Attribute = apps.get_model('typeclasses', 'Attribute')
    ObjectDB = apps.get_model('objects', 'ObjectDB')
    PlayerDB = apps.get_model('players', 'PlayerDB')
    ScriptDB = apps.get_model('scripts', 'ScriptDB')
    HelpEntry = apps.get_model('help', 'HelpEntry')
    Msg = apps.get_model('comms', 'Msg')





class Migration(migrations.Migration):

    dependencies = [
        ('typeclasses', '0005_auto_20160625_1812'),
    ]

    operations = [
            migrations.RunPython(update_tags_with_dbmodel)
    ]
