# Generated by Django 3.0.3 on 2020-02-10 02:48

from django.db import migrations
import evennia.accounts.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0018_auto_20191025_0831'),
        ('objects', '0011_auto_20191025_0831'),
        ('accounts', '0009_auto_20191025_0831'),
        ('scripts', '0014_auto_20200210_0248'),
        ('typeclasses', '0013_auto_20191015_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.accountdb',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultChannel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('comms.channeldb',),
        ),
        migrations.CreateModel(
            name='DefaultObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objects.objectdb',),
        ),
        migrations.CreateModel(
            name='ScriptBase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scripts.scriptdb',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultaccount',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultaccount',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultchannel',),
        ),
        migrations.CreateModel(
            name='DefaultCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultobject',),
        ),
        migrations.CreateModel(
            name='DefaultExit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultobject',),
        ),
        migrations.CreateModel(
            name='DefaultGuest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultaccount',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultRoom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultobject',),
        ),
        migrations.CreateModel(
            name='DefaultScript',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.scriptbase',),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultobject',),
        ),
        migrations.CreateModel(
            name='BotStarter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultcharacter',),
        ),
        migrations.CreateModel(
            name='DbPrototype',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
        migrations.CreateModel(
            name='DoNothing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultexit',),
        ),
        migrations.CreateModel(
            name='GrapevineBot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.bot',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultguest',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='IRCBot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.bot',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultroom',),
        ),
        migrations.CreateModel(
            name='RSSBot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.bot',),
            managers=[
                ('objects', evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
        migrations.CreateModel(
            name='TimeScript',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('typeclasses.defaultscript',),
        ),
    ]
