# Generated by Django 5.1.6 on 2025-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typeclasses", "0016_alter_attribute_id_alter_tag_id"),
    ]

    operations = [
        # First create the index with the old name that Django expects
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["db_key", "db_category", "db_tagtype", "db_model"],
                name="typeclasses_tag_db_key_db_category_db_tagtype_db_model_idx",
            ),
        ),
        # Then rename it to the new name
        migrations.RenameIndex(
            model_name="tag",
            new_name="typeclasses_db_key_be0c81_idx",
            old_fields=("db_key", "db_category", "db_tagtype", "db_model"),
        ),
    ]
