# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_auto_20160905_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='db_hide_from_channels',
            field=models.ManyToManyField(blank=True, null=True, related_name='hide_from_channels_set', to='comms.ChannelDB'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_hide_from_objects',
            field=models.ManyToManyField(blank=True, null=True, related_name='hide_from_objects_set', to='objects.ObjectDB'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_hide_from_players',
            field=models.ManyToManyField(blank=True, null=True, related_name='hide_from_players_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_receivers_channels',
            field=models.ManyToManyField(blank=True, help_text=b'channel recievers', null=True, related_name='channel_set', to='comms.ChannelDB'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_receivers_objects',
            field=models.ManyToManyField(blank=True, help_text=b'object receivers', null=True, related_name='receiver_object_set', to='objects.ObjectDB'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_receivers_players',
            field=models.ManyToManyField(blank=True, help_text=b'player receivers', null=True, related_name='receiver_player_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_sender_external',
            field=models.CharField(blank=True, db_index=True, help_text=b"identifier for external sender, for example a sender over an IRC connection (i.e. someone who doesn't have an exixtence in-game).", max_length=255, null=True, verbose_name=b'external sender'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_sender_objects',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='sender_object_set', to='objects.ObjectDB', verbose_name=b'sender(object)'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_sender_players',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='sender_player_set', to=settings.AUTH_USER_MODEL, verbose_name=b'sender(player)'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='db_tags',
            field=models.ManyToManyField(blank=True, help_text=b'tags on this message. Tags are simple string markers to identify, group and alias messages.', null=True, to='typeclasses.Tag'),
        ),
    ]
