# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:36
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):

    try:
        AccountDB = apps.get_model('accounts', 'AccountDB')
    except LookupError:
        return

    Msg = apps.get_model('comms', 'Msg')
    for msg in Msg.objects.all():
        for account in msg.db_sender_accounts.all():
            account = AccountDB.objects.get(id=account.id)
            msg.db_sender_accounts.add(account)
        for account in msg.db_receivers_accounts.all():
            account = AccountDB.objects.get(id=account.id)
            msg.db_receivers_accounts.add(account)
        for account in msg.db_hide_from_accounts.all():
            account = AccountDB.objects.get(id=account.id)
            msg.db_hide_from_accounts.add(account)

    ChannelDB = apps.get_model('comms', 'ChannelDB')
    for channel in ChannelDB.objects.all():
        for account in channel.db_subscriptions.all():
            account = AccountDB.objects.get(id=account.id)
            channel.db_account_subscriptions.add(account)


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0013_auto_20170705_1726'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
