# Generated by Django 4.0.2 on 2022-10-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0021_auto_20210520_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channeldb",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
