# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:41
from __future__ import unicode_literals

from django.db import migrations, OperationalError, connection


def _table_exists(db_cursor, tablename):
    "Returns bool if table exists or not"
    sql_check_exists = "SELECT * from %s;" % tablename
    try:
        db_cursor.execute(sql_check_exists)
        return True
    except OperationalError:
        return False


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_auto_20170705_1736'),
    ]

    db_cursor = connection.cursor()

    if not _table_exists(db_cursor, 'scripts_scriptdb_db_player'):
        operations = []
    else:
        operations = [
            migrations.RemoveField(
                model_name='scriptdb',
                name='db_player',
            ),
        ]
