# Generated by Django 3.0.3 on 2020-02-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0013_auto_20191025_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptdb',
            options={'ordering': ['db_key'], 'verbose_name': 'Script'},
        ),
    ]
