# evennia/setup-database

# Use this action in a workflow for when you need to do initialization of database services
# (such as with PostgreSQL and MySQL) before you initiate unit tests that will employ that
# database service.

# NOTE: This action was intended for use with the core Evennia workflows ONLY.

name: Set up Evennia database service
author: dvoraen
description: "Activates the database server for the passed in service and ensures it's ready for use."

inputs:
  database:
    description: "Database service being initialized."
    required: true

runs:
  using: "composite"

  steps:
    - name: Wait for PostgreSQL to be ready
      if: ${{ inputs.database == 'postgresql' }}
      run: |
        # Wait for PostgreSQL service container to be healthy
        until pg_isready -h localhost -U evennia -d evennia; do
          sleep 1
          echo -n .
        done
        echo "PostgreSQL is ready"
      shell: bash
      env:
        PGPASSWORD: password

    - name: Wait for MySQL to be ready
      if: ${{ inputs.database == 'mysql' }}
      run: |
        # Wait for MySQL service container to be healthy
        until mysqladmin ping -h 127.0.0.1 -u root -proot_password --silent; do
          sleep 1
          echo -n .
        done
        echo "MySQL is ready"
      shell: bash

    - name: Set up MySQL Privileges
      if: ${{ inputs.database == 'mysql' }}
      run: |
        # Note: MySQL server configuration (character set, collation, row format) is set
        # at container startup via custom entrypoint script that passes command-line arguments
        # to mysqld, similar to how mirromutth/mysql-action works.
        # Ensure user exists and has proper privileges
        mysql -u root -proot_password -h 127.0.0.1 mysql <<EOF
        CREATE USER IF NOT EXISTS 'evennia'@'%' IDENTIFIED BY 'password';
        GRANT ALL PRIVILEGES ON \`evennia%\`.* TO 'evennia'@'%';
        GRANT PROCESS ON *.* TO 'evennia'@'%';
        GRANT SESSION_VARIABLES_ADMIN ON *.* TO 'evennia'@'%';
        FLUSH PRIVILEGES;
        EOF
        # Set database character set and collation
        mysql -u root -proot_password -h 127.0.0.1 evennia <<EOF
        ALTER DATABASE evennia CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        EOF
      shell: bash

    # get logs from db start
    - name: Database container logs
      if: ${{ inputs.database == 'postgresql' || inputs.database == 'mysql' }}
      uses: jwalton/gh-docker-logs@v2

    - name: Check running containers
      if: ${{ inputs.database == 'postgresql' || inputs.database == 'mysql' }}
      run: docker ps -a
      shell: bash
