# Generated by Django 2.1.8 on 2019-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190128_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdb',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
