# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aisystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorblackboarddb',
            name='db_agent',
        ),
        migrations.RemoveField(
            model_name='behaviorblackboarddb',
            name='db_tree',
        ),
        migrations.DeleteModel(
            name='BehaviorBlackboardDB',
        ),
        migrations.DeleteModel(
            name='BehaviorTreeDB',
        ),
    ]
