# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('aisystem', '0002_auto_20160915_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorBlackboardDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(db_index=True, max_length=80, verbose_name='key')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('db_running_now', models.TextField(blank=True, default='[]', null=True, verbose_name='active')),
                ('db_running_pre', models.TextField(blank=True, default='[]', null=True, verbose_name='active pre')),
                ('db_nodes', models.TextField(blank=True, default='{}', null=True, verbose_name='node data')),
                ('db_global', models.TextField(blank=True, default='{}', null=True, verbose_name='global data')),
                ('db_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB', verbose_name='agent')),
            ],
            options={
                'verbose_name': 'behavior blackboard',
            },
        ),
        migrations.CreateModel(
            name='BehaviorTreeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(db_index=True, max_length=80, verbose_name='key')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('db_root', models.TextField(blank=True, null=True, verbose_name='root')),
                ('db_nodes', models.TextField(blank=True, default='{}', null=True, verbose_name='node dict')),
            ],
            options={
                'verbose_name': 'behavior tree',
            },
        ),
        migrations.AddField(
            model_name='behaviorblackboarddb',
            name='db_tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aisystem.BehaviorTreeDB', verbose_name='tree'),
        ),
    ]
