"""
Writing what the developer accepted, where it cannot do any harm.

WHERE IT GOES, AND WHY NOT ANYWHERE ELSE. Everything lands in `aetos-discovery/`
inside the game directory, and nothing there is ever imported: not by Aetos, not
by Evennia, not by the game (Addendum B.44). The developer copies what they want
into `settings.py` themselves.

That is a deliberate refusal of the more helpful-looking design. A tool that
edits `settings.py` has to be trusted *before* it is understood, which is the
wrong way round for the first thing somebody runs against their own game, and it
turns a wrong guess into a broken server rather than a file they can delete.

THREE FILES, PER B.41-B.44::

    aetos-discovery/
    ├── report.txt               what was read, found, accepted and ignored
    ├── suggested_bindings.py    the accepted candidates, pasteable
    └── suggested_provider.py    only when a provider is the honest answer

The provider file is **starter code and says so in capitals**, because static
analysis cannot know what a game means by `character.stats.get("health")`. It is
a skeleton with the handler's name in it, not a working integration, and it
would be worse than nothing if it looked finished.

WHAT IS NEVER WRITTEN: a credential. The withheld names travel with the
candidate set so the report can say one was withheld, and the value is never
read in the first place -- see `redaction`.

"""

import ast
import datetime
import json
import os

from evennia.contrib.base_systems.aetos_webclient.discovery import redaction, roots

#: The directory generated files are written to, inside the game directory.
OUTPUT_DIRECTORY = "aetos-discovery"

#: What the three files are called (B.44).
REPORT_FILE = "report.txt"
BINDINGS_FILE = "suggested_bindings.py"
PROVIDER_FILE = "suggested_provider.py"

#: The label a generated provider carries, in the words the addendum uses.
STARTER_WARNING = "STARTER CODE -- REVIEW BEFORE USE"

PROVIDER_TEMPLATE = '''"""
%(warning)s

Generated by `evennia aetos setup` on %(when)s.

Nothing imports this file. Move it into your game (for example
`world/aetos_providers.py`), finish the parts marked REPLACE, and register it::

    AETOS_PROVIDERS = {"resources": "world.aetos_providers.GameResourceProvider"}

WHY A PROVIDER AND NOT A BINDING. A binding names *where* a value is stored and
Aetos reads it directly. These values are produced by calling something, and
Aetos never calls anything to read a value -- that is what this class is for.

What discovery saw:

%(findings)s
"""

from evennia.contrib.base_systems.aetos_webclient.providers import base


class GameResourceProvider(base.AetosResourceProvider):
    """%(warning)s -- resources for this game."""

    name = "game resources"

    def get_resources(self, character):
        """
        The resources to show for a character.

        Args:
            character (Object): The character being described.

        Returns:
            list: One dict per resource, each with at least `id`, `label` and
                `value`, and `maximum` where there is a ceiling.

        """
        # REPLACE: read your game's own values here. Return an empty list
        # when a character has none -- Aetos shows nothing rather than a bar
        # with no number in it.
        return []
'''


def output_directory(gamedir=None):
    """
    Where generated files go.

    Args:
        gamedir (str, optional): The game directory.

    Returns:
        str: Absolute path to `aetos-discovery/` inside the game directory.

    Raises:
        ScanRootError: If that path would land outside the game directory,
            which means an assumption is wrong and writing would be worse than
            stopping.

    """
    base = os.path.realpath(gamedir) if gamedir else roots.game_directory()
    target = os.path.join(base, OUTPUT_DIRECTORY)
    if not roots.is_inside(target, base):
        raise roots.ScanRootError(
            "%s resolves outside the game directory (%s), so nothing was written." % (target, base)
        )
    return target


def _timestamp(when=None):
    """
    The time a run happened, as the report prints it.

    Args:
        when (datetime, optional): Supplied by tests so output is comparable.

    Returns:
        str: e.g. `2026-09-11 18:47`.

    """
    return (when or datetime.datetime.now()).strftime("%Y-%m-%d %H:%M")


def _literal(value):
    """
    A value as Python source, in the quotes Evennia's own code uses.

    Args:
        value: A string or other literal.

    Returns:
        str: e.g. `"db.hp"`. Double-quoted, because `repr` gives single quotes
            and `black` -- which Evennia's CI runs -- would rewrite every line
            of a generated file the moment it was pasted in (B.41).

    """
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def bindings_source(accepted, when=None):
    """
    The text of `suggested_bindings.py`.

    Args:
        accepted (dict): Slot -> {key -> entry}, as the wizard collected them.
        when (datetime, optional): Timestamp for the header.

    Returns:
        str: Python source, which parses and evaluates to the same dictionary.

    Notes:
        Built with `repr` on plain data rather than by string-pasting values, so
        a label containing a quote cannot produce a file that will not parse.

    """
    lines = [
        '"""',
        "Suggested by `evennia aetos setup` on %s." % _timestamp(when),
        "",
        "Nothing imports this file. Copy what you want into",
        "server/conf/settings.py and delete the rest.",
        '"""',
        "",
        "AETOS_BINDINGS = {",
    ]
    for slot, entries in accepted.items():
        if not entries:
            continue
        lines.append("    %s: {" % _literal(slot))
        for key, entry in entries.items():
            lines.append("        %s: {" % _literal(key))
            for field, value in entry.items():
                lines.append("            %s: %s," % (_literal(field), _literal(value)))
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def provider_source(findings, when=None):
    """
    The text of `suggested_provider.py`.

    Args:
        findings (list): Lines describing what could not be bound.
        when (datetime, optional): Timestamp for the header.

    Returns:
        str: Python source, labelled as starter code.

    """
    body = "\n".join("  - %s" % finding for finding in findings) or "  - (nothing recorded)"
    return PROVIDER_TEMPLATE % {
        "warning": STARTER_WARNING,
        "when": _timestamp(when),
        "findings": body,
    }


def report_source(context, accepted, ignored, problems, generated, when=None):
    """
    The text of `report.txt` (B.45).

    Args:
        context (dict): `gamedir`, `characters`, `lineages`, `files_read`.
        accepted (list): Lines naming what was accepted.
        ignored (list): Lines naming what was ignored.
        problems (iterable): Warnings and notes from the scans.
        generated (list): File names written.
        when (datetime, optional): Timestamp.

    Returns:
        str: The report.

    """

    def section(title, rows):
        """
        One titled block, or a line saying it is empty.

        Args:
            title (str): The heading.
            rows (iterable): Lines.

        Returns:
            list: Lines to append.

        """
        out = ["", title, "-" * len(title)]
        if rows:
            out.extend("  %s" % row for row in rows)
        else:
            out.append("  (none)")
        return out

    lines = [
        "Aetos discovery report",
        "======================",
        "",
        "Generated: %s" % _timestamp(when),
        "Game:      %s" % context.get("gamedir", ""),
    ]
    if context.get("characters"):
        lines.append("Read:      %s" % ", ".join(context["characters"]))
    for chain in context.get("lineages") or []:
        lines.append("Typeclass: %s" % " <- ".join(chain))
    if context.get("files_read") is not None:
        lines.append("Files:     %d read" % context["files_read"])

    lines.extend(section("Accepted", accepted))
    lines.extend(section("Ignored", ignored))
    lines.extend(section("Notes and warnings", list(problems)))
    lines.extend(section("Written", generated))
    lines.extend(
        [
            "",
            "Nothing here has been applied. Aetos does not edit settings.py, and no",
            "file in this directory is imported by anything.",
        ]
    )
    return "\n".join(lines) + "\n"


def write(gamedir, report, bindings=None, provider=None):
    """
    Write the generated files.

    Args:
        gamedir (str): The game directory.
        report (str): `report.txt`'s content.
        bindings (str, optional): `suggested_bindings.py`'s content.
        provider (str, optional): `suggested_provider.py`'s content.

    Returns:
        list: The paths written, in a stable order.

    Raises:
        ScanRootError: If the output directory is not inside the game.

    Notes:
        Each generated Python file is parsed before it is written. A generator
        that emits something that will not parse has failed at the one thing it
        is for, and finding that out in the developer's editor is finding out
        late. Parsed, never executed: a check that ran the file would pass on a
        file that also did something else.

    """
    for source in (bindings, provider):
        if source is not None:
            ast.parse(source)

    directory = output_directory(gamedir)
    os.makedirs(directory, exist_ok=True)

    written = []
    for name, content in (
        (REPORT_FILE, report),
        (BINDINGS_FILE, bindings),
        (PROVIDER_FILE, provider),
    ):
        if content is None:
            continue
        path = os.path.join(directory, name)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        written.append(path)
    return written


def contains_secret(text, withheld):
    """
    Whether generated text mentions a withheld name.

    Args:
        text (str): Generated content.
        withheld (iterable): Names refused by `redaction`.

    Returns:
        bool: True if any appears. Used as a last check before writing, because
            the cost of being wrong here is a credential in a file somebody
            commits.

    """
    return any(name in text for name in withheld if redaction.is_sensitive(name))
