from evennia.utils.logger import *
from twisted.internet.threads import deferToThread
import json

def output(data, *args, **kwargs):
    """
    Writes dictionaries of data generated by an AuditedServerSession to files 
    in JSON format, bucketed by date.
    
    Uses Evennia's native logger and writes to the default 
    log directory (~/yourgame/server/logs/ or settings.LOG_DIR)

    Args:
        data (dict): Parsed session transmission data.

    """
    # Bucket logs by day
    bucket = data.pop('objects')['time'].strftime('%Y-%m-%d')
    
    # Write it
    log_file(json.dumps(data), filename="auditing_%s.log" % bucket)
    