# This Evennia workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-suite

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    uses: ./.github/workflows/github_action_base_workflow.yml
    with:
      # To workaround github reusable workflows inputs limitations this needs to be a JSON string,
      # it will be parsed later in reusable workflow itself.
      python-matrix: '["3.9", "3.10"]'
    secrets: inherit
